### ISSUE TITLE
Need the posts that the user still doesn't has access be hidden in blog, search and archive pages.

### ISSUE THREAD

**Issue by danielbike** [eighty20results/pmpro-sequence#1]
Hi,
How to hide the posts that the user still doesnt have access because of the date?
Example, if the "post 02" is set up in the plugin to delay 2 days, in those 2 day, i would like that it does not show in the blog or archive pages. 

How can i do that?

Thanks a lot..

**Comment by eighty20results** [comment]
You would click the "Hide future posts" in the settings (top right on the /wp-admin/ edit page for that sequence)/

**Comment by Erudition** [comment]
Need this as well. The posts are not hidden from the pages described, the links still work! The only place future posts are hidden by the option you mention, is the sequence page. Everywhere else in the theme, the post titles and links are visible, which in my case is a big no-no since the titles contain spoilers.

And the sequence list widget is way too simplistic and hard to style, to take the place of every article list on my site....
